twig:
    file_name_pattern: "*.twig"
    form_themes: ["@Flowbite/form/default.html.twig"]

    globals:
        sx_url_github: "https://github.com/symfony-x"
        sx_url_license: "https://github.com/symfony-x/symfony-x/blob/master/LICENSE"
        sx_url_symfony: "https://symfony.com"
        sx_url_tailwind: "https://tailwindcss.com/"
        sx_url_flowbite: "https://flowbite.com/"
        sx_url_turbo: "https://turbo.hotwired.dev/"
        sx_url_stimulus: "https://stimulus.hotwired.dev/"
        sx_url_live: "https://live.hotwired.dev/"
        sx_url_assetmapper: "https://symfony.com/doc/current/frontend/asset_mapper.html"

when@test:
    twig:
        strict_variables: true
