twig:
    file_name_pattern: "*.twig"
    form_themes: ["@Flowbite/form/default.html.twig"]

    globals:
        sx_github_url: "https://github.com/symfony-x"
        sx_symfony_url: "https://symfony.com"
        sx_tailwind_url: "https://tailwindcss.com/"
        sx_flowbite_url: "https://flowbite.com/"
        sx_turbo_url: "https://turbo.hotwired.dev/"
        sx_stimulus_url: "https://stimulus.hotwired.dev/"
        sx_live_url: "https://live.hotwired.dev/"
        sx_assetmapper_url: "https://symfony.com/doc/current/frontend/asset_mapper.html"

when@test:
    twig:
        strict_variables: true
